cmd_/home/heigon77/Facul/MC504/staging/tools/objtool/builtin-check.o := gcc -Wp,-MD,/home/heigon77/Facul/MC504/staging/tools/objtool/.builtin-check.o.d -Wp,-MT,/home/heigon77/Facul/MC504/staging/tools/objtool/builtin-check.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wno-type-limits -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wno-nested-externs -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -g -I/home/heigon77/Facul/MC504/staging/tools/include -I/home/heigon77/Facul/MC504/staging/tools/arch/x86/include/uapi -I/home/heigon77/Facul/MC504/staging/tools/arch/x86/include -I/home/heigon77/Facul/MC504/staging/tools/objtool/include -I/home/heigon77/Facul/MC504/staging/tools/objtool/arch/x86/include -I/home/heigon77/Facul/MC504/staging/tools/lib -D"BUILD_STR(s)=$(pound)s" -c -o /home/heigon77/Facul/MC504/staging/tools/objtool/builtin-check.o builtin-check.c

source_/home/heigon77/Facul/MC504/staging/tools/objtool/builtin-check.o := builtin-check.c

deps_/home/heigon77/Facul/MC504/staging/tools/objtool/builtin-check.o := \
  /usr/include/stdc-predef.h \
  /home/heigon77/Facul/MC504/staging/tools/lib/subcmd/parse-options.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-linux-gnu/9/include/stdarg.h \
  /usr/lib/gcc/x86_64-linux-gnu/9/include/stddef.h \
  /usr/include/assert.h \
  /usr/include/features.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/build_bug.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/compiler.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/compiler_types.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/compiler-gcc.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/9/include/stdbool.h \
  /usr/lib/gcc/x86_64-linux-gnu/9/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/timesize.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/time64.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/heigon77/Facul/MC504/staging/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitsperlong.h \
  /home/heigon77/Facul/MC504/staging/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endianness.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/byteswap.h \
  /usr/include/string.h \
  /usr/include/x86_64-linux-gnu/bits/types/locale_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/x86_64-linux-gnu/bits/strings_fortified.h \
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/x86_64-linux-gnu/bits/floatn.h \
  /usr/include/x86_64-linux-gnu/bits/floatn-common.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/x86_64-linux-gnu/bits/struct_mutex.h \
  /usr/include/x86_64-linux-gnu/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib.h \
  /home/heigon77/Facul/MC504/staging/tools/objtool/include/objtool/builtin.h \
  /home/heigon77/Facul/MC504/staging/tools/objtool/include/objtool/objtool.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/list.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/poison.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/hashtable.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/bitops.h \
  /usr/lib/gcc/x86_64-linux-gnu/9/include/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/9/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
  /usr/include/x86_64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/bits.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/const.h \
  /home/heigon77/Facul/MC504/staging/tools/include/vdso/const.h \
  /home/heigon77/Facul/MC504/staging/tools/include/uapi/linux/const.h \
  /home/heigon77/Facul/MC504/staging/tools/include/vdso/bits.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/__ffs.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/__ffz.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/fls.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/__fls.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/fls64.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/find.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/hweight.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/arch_hweight.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/const_hweight.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/atomic.h \
  /home/heigon77/Facul/MC504/staging/tools/include/asm-generic/bitops/non-atomic.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/hash.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/log2.h \
  /home/heigon77/Facul/MC504/staging/tools/objtool/include/objtool/elf.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/elf.h \
  /usr/include/x86_64-linux-gnu/bits/auxv.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/rbtree.h \
  /usr/include/linux/stddef.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/jhash.h \
  /home/heigon77/Facul/MC504/staging/tools/include/linux/unaligned/packed_struct.h \

/home/heigon77/Facul/MC504/staging/tools/objtool/builtin-check.o: $(deps_/home/heigon77/Facul/MC504/staging/tools/objtool/builtin-check.o)

$(deps_/home/heigon77/Facul/MC504/staging/tools/objtool/builtin-check.o):
